default_language_version:
  python: python3
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      # Run the linter.
      - id: ruff
        exclude: ^(docs/|test/|examples/) # only check package_name
      # Run the formatter.
      - id: ruff-format
        exclude: ^(docs/|test/|examples/) # only check package_name
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-added-large-files
        args: [ "--maxkb=1000" ]
      - id: mixed-line-ending
        args: ["--fix=auto"]
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-toml
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
      -   id: poetry-check
      -   id: poetry-lock
          args: [--no-update]
